project:
  type: website
  output-dir: docs

website:
  title: "GAPMED Insights"
  favicon: assets/favicon.png
  navbar:
    logo: assets/logo.png
  page-footer:
    center: "Â© 2025 GAPMED Insights. Tutti i diritti riservati."

format:
  html:
    theme:
      light: flatly
    css: custom-style.css
    toc: true
    toc-title: "In questa pagina"
    toc-location: right
    page-layout: full
    grid:
      body-width: 1200px
    include-in-header: includes/gtm-head.html
    include-before-body: includes/gtm-body.html
